name: The Bountiful Garden
favicon: null
layout_spectrum: 0.3634686917066574
typography_spectrum: 0.7382568276952952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15697923419065773
  lightness: 0.4668136974796653
  saturation: 0.10189752886071801
  rhythmicContrast: 0.837022555526346
purpose: []
